// Export
export default Object.freeze({
  ONBOARDING: "OnboardingScreen",
  HOME_NAVIGATOR: "HomeNavigator",
  ACCOUNT_NAVIGATOR: "AccountNavigator",
  HOME: "HomeScreen",
  ACCOUNT: "AccountScreen",
  LOGIN: "LoginScreen",
  REGISTER: "RegisterScreen",
  PASSWORD_RECOVERY: "PasswordRecoveryScreen",
  EDIT_PROFILE: "EditProfileScreen",
  SEARCH_CARS_NAVIGATOR: "SearchCarsNavigator",
  SEARCH_CARS: "SearchCarsScreen",
  POST_CAR_NAVIGATOR: "PostCarNavigator",
  POST_CAR: "PostCarScreen",
  SAVED_NAVIGATOR: "SavedNavigator",
  SAVED: "SavedScreen",
  CAR_DETAILS: "CarDetailsScreen",
  CAR_BOOKING: "CarBookingScreen",
  CAR_CHECKOUT: "CarCheckoutScreen",
  CAR_COMPLETE: "CarCompleteScreen",
  ORDERS: "OrdersScreen",
  ORDER_DETAILS: "OrderDetailsScreen",
});
